apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: dispatcher-service

resources:
  - deployment.yml
  - service.yml

configMapGenerator:
  - name: dispatcher-service
    files:
      - application.yml

secretGenerator:
  - name: dispatcher-service
    literals:
      - spring.cloud.config.username=user
      - spring.cloud.config.password=password
