apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quote-service
spec:
  template:
    spec:
      containers:
        - name: quote-service
          image: quote-service
          ports:
            - containerPort: 9101
          resources:
            requests:
              cpu: '0.1'
              memory: '128Mi'
            limits:
              cpu: '1'
              memory: '512Mi'
