spring:
  config:
    import: configserver:,configtree:/workspace/secrets/*/
  cloud:
    config:
      fail-fast: true
  flyway:
    url: jdbc:postgresql://polar-postgres.postgres.database.azure.com:5432/polardb_order
  r2dbc:
    url: r2dbc:postgresql://polar-postgres.postgres.database.azure.com:5432/polardb_order
  rabbitmq:
    host: polar-rabbitmq.rabbitmq-system.svc.cluster.local
    port: 5672
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://82369d949ea44f80943e.northeurope.aksapp.io/auth/realms/PolarBookshop
