apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
data:
  application.yml: |
    polar:
      greeting: Welcome to the book catalog from Kubernetes!
    spring:
      config:
        import:
      cloud:
        config:
          enabled: false
      datasource:
        url: jdbc:postgresql://polar-postgres/polardb_catalog
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://polar-keycloak/auth/realms/PolarBookshop
