apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher-service
  template:
    spec:
      containers:
        - name: dispatcher-service
          image: dispatcher-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9003
          volumeMounts:
            - name: dispatcher-service-volume
              mountPath: /workspace/config
      volumes:
        - name: dispatcher-service-volume
          configMap:
            name: dispatcher-service
