apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
spec:
  template:
    spec:
      containers:
        - name: dispatcher-service
          volumeMounts:
            - name: config-credentials-volume
              mountPath: /workspace/secrets/config
            - name: rabbitmq-credentials-volume
              mountPath: /workspace/secrets/rabbitmq
      volumes:
        - name: config-credentials-volume
          secret:
            secretName: config-credentials
        - name: rabbitmq-credentials-volume
          secret:
            secretName: polar-rabbitmq-credentials
