apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quote-function
spec:
  template:
    spec:
      containers:
        - name: quote-function
          image: quote-function
          ports:
            - containerPort: 9102
          resources:
            requests:
              cpu: '0.1'
              memory: '128Mi'
            limits:
              cpu: '1'
              memory: '512Mi'
