spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-service
  datasource:
    url: jdbc:postgresql://polar-postgres-catalog/polardb_catalog
  rabbitmq:
    host: polar-rabbitmq
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8080/auth/realms/PolarBookshop
