apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: config-service

resources:
  - deployment.yml
  - service.yml

configMapGenerator:
  - name: config-service
    files:
      - application.yml
